// ui/src/components/Step1SourceName.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  
  export let sourceName: string = '';
  export let onSourceNameChange: (name: string) => void;
  export let recentSources: string[] = [];
  
  let showSuggestions = false;
  let inputElement: HTMLInputElement;
  let filteredSuggestions: string[] = [];
  
  function handleFocus() {
    showSuggestions = true;
    updateFilteredSuggestions(sourceName);
  }
  
  function handleSelect(name: string) {
    sourceName = name;
    onSourceNameChange(name);
    showSuggestions = false;
  }
  
  function updateFilteredSuggestions(search: string) {
    filteredSuggestions = recentSources.filter((s) =>
      s.toLowerCase().includes(search.toLowerCase())
    );
  }
  
  function handleClickOutside(event: MouseEvent) {
    const target = event.target as Node;
    if (inputElement && !inputElement.contains(target)) {
      // Check if click is inside suggestions container
      const suggestionsContainer = document.querySelector('.suggestions');
      if (!suggestionsContainer || !suggestionsContainer.contains(target)) {
        showSuggestions = false;
      }
    }
  }
  
  onMount(() => {
    document.addEventListener('mousedown', handleClickOutside);
    updateFilteredSuggestions(sourceName);
  });
  
  onDestroy(() => {
    document.removeEventListener('mousedown', handleClickOutside);
  });
  
  $: if (sourceName !== undefined) {
    updateFilteredSuggestions(sourceName);
  }
</script>

<div style="display: flex; flex-direction: column; gap: 12px;">
  <label for="source-name-input" style="display: block; font-size: 14px; font-weight: 600; color: var(--fg); display: flex; align-items: center; gap: 8px;">
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
      <circle cx="12" cy="12" r="10"></circle>
      <circle cx="12" cy="12" r="3"></circle>
    </svg>
    Step 1: Nome della Source
  </label>
  
  <div style="position: relative;">
    <input
      id="source-name-input"
      bind:this={inputElement}
      type="text"
      bind:value={sourceName}
      on:input={(e) => {
        const value = e.currentTarget.value;
        onSourceNameChange(value);
        showSuggestions = true;
        updateFilteredSuggestions(value);
      }}
      on:focus={handleFocus}
      placeholder="Inserisci il nome della source..."
      class="source-input"
      class:has-suggestions={showSuggestions && filteredSuggestions.length > 0}
      class:has-value={sourceName.trim() !== ''}
    />
    
    {#if showSuggestions && filteredSuggestions.length > 0}
      <div class="suggestions" role="listbox">
        {#each filteredSuggestions as suggestion}
          <button
            type="button"
            on:click|preventDefault|stopPropagation={() => handleSelect(suggestion)}
            class="suggestion-item"
            role="option"
            aria-selected={sourceName === suggestion}
          >
            {suggestion}
          </button>
        {/each}
      </div>
    {/if}
  </div>
</div>

<style>
  .source-input {
    width: 100%;
    height: 44px;
    padding: 0 16px;
    border: 1px solid var(--input-border);
    border-radius: 12px !important;
    background: var(--input-bg);
    color: var(--fg);
    font-size: 14px;
    transition: all 0.2s;
    backdrop-filter: blur(30px);
    -webkit-backdrop-filter: blur(30px);
  }
  
  .source-input::placeholder {
    color: rgba(255, 255, 255, 0.5);
  }
  
  .source-input:focus {
    outline: none;
    border-color: var(--input-focus);
    box-shadow: 0 0 0 3px rgba(10, 132, 255, 0.15);
  }
  
  .source-input.has-suggestions {
    border-color: var(--input-focus);
    box-shadow: 0 0 0 2px rgba(10, 132, 255, 0.3);
  }
  
  .source-input.has-value {
    background: var(--input-bg);
  }
  
  .source-input:not(.has-value) {
    background: var(--input-bg);
    color: rgba(255, 255, 255, 0.7);
  }
  
  .suggestions {
    position: absolute;
    z-index: 10;
    width: 100%;
    margin-top: 4px;
    background: rgba(100, 100, 110, 0.15);
    border: 1px solid var(--border);
    border-radius: 12px !important;
    box-shadow: 0 8px 24px rgba(0, 0, 0, 0.4);
    max-height: 192px;
    overflow-y: auto;
    backdrop-filter: blur(20px);
    -webkit-backdrop-filter: blur(20px);
  }
  
  .suggestions::-webkit-scrollbar {
    width: 5px;
  }
  
  .suggestions::-webkit-scrollbar-track {
    background: transparent;
  }
  
  .suggestions::-webkit-scrollbar-thumb {
    background: var(--bar-fill);
    border-radius: 3px;
  }
  
  .suggestion-item {
    width: 100%;
    padding: 8px 16px;
    text-align: left;
    background: transparent;
    border: none;
    color: var(--fg);
    transition: background-color 0.2s;
    font-size: 14px;
  }
  
  .suggestion-item:hover {
    background: rgba(255, 255, 255, 0.15);
  }
  
  .suggestion-item:first-child {
    border-top-left-radius: 12px;
    border-top-right-radius: 12px;
  }
  
  .suggestion-item:last-child {
    border-bottom-left-radius: 12px;
    border-bottom-right-radius: 12px;
  }
</style>

// src/components/Step1SourceName.tsx
import { useState, useEffect, useRef } from "react";
import { Target } from "lucide-react";

interface Step1SourceNameProps {
  sourceName: string;
  onSourceNameChange: (name: string) => void;
  recentSources: string[];
}

export default function Step1SourceName({
  sourceName,
  onSourceNameChange,
  recentSources,
}: Step1SourceNameProps) {
  const [showSuggestions, setShowSuggestions] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (
        inputRef.current &&
        !inputRef.current.contains(event.target as Node)
      ) {
        setShowSuggestions(false);
      }
    };

    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  const handleSelect = (name: string) => {
    onSourceNameChange(name);
    setShowSuggestions(false);
  };

  const filteredSuggestions = recentSources.filter((s) =>
    s.toLowerCase().includes(sourceName.toLowerCase())
  );

  return (
    <div className="space-y-3">
      <label className="block text-sm font-semibold text-white flex items-center gap-2">
        <Target className="w-4 h-4" />
        Step 1: Nome della Source
      </label>
      <div className="relative" ref={inputRef}>
        <input
          type="text"
          value={sourceName}
          onChange={(e) => {
            onSourceNameChange(e.target.value);
            setShowSuggestions(true);
          }}
          onFocus={() => setShowSuggestions(true)}
          placeholder="Inserisci il nome della source..."
          className={`w-full h-11 px-4 border transition-all text-white ${
            showSuggestions && filteredSuggestions.length > 0
              ? "border-blue-400 ring-2 ring-blue-400/30"
              : "border-white/20"
          } ${
            sourceName
              ? "bg-black/8 backdrop-blur-glass"
              : "bg-black/6 backdrop-blur-glass text-white/70"
          } focus:outline-none focus:ring-2 focus:ring-white/30 placeholder:text-white/50`}
        />
        {showSuggestions && filteredSuggestions.length > 0 && (
          <div className="absolute z-10 w-full mt-1 backdrop-blur-glass border border-white/20 rounded-xl shadow-lg max-h-48 overflow-y-auto hide-scrollbar">
            {filteredSuggestions.map((suggestion, index) => (
              <button
                key={index}
                onClick={() => handleSelect(suggestion)}
                className="w-full px-4 py-2 text-left hover:bg-white/20 text-white transition-colors first:rounded-t-xl last:rounded-b-xl"
              >
                {suggestion}
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
