// src/components/TitleBar.tsx
import { X, Minus } from "lucide-react";
import { appWindow } from "@tauri-apps/api/window";

export default function TitleBar() {
  const handleClose = () => {
    appWindow.close();
  };

  const handleMinimize = () => {
    appWindow.minimize();
  };


  return (
    <div
      className="h-14 flex items-center justify-between px-5 border-b border-white/20 flex-shrink-0 relative"
      style={{
        backgroundColor: 'rgba(0, 0, 0, 0.08)',
        backdropFilter: 'blur(12px) saturate(180%)',
        WebkitBackdropFilter: 'blur(12px) saturate(180%)',
        borderTopLeftRadius: '10px',
        borderTopRightRadius: '10px',
        overflow: 'hidden',
      }}
      data-tauri-drag-region
    >
      {/* Title - centered */}
      <div
        className="absolute left-0 right-0 top-0 bottom-0 flex items-center justify-center gap-2 font-bold text-base text-white pointer-events-none"
        data-tauri-drag-region
      >
        <img src="/icon.ico" alt="File Extractor Icon" className="w-5 h-5" />
        File Extractor
      </div>

      {/* Window controls on the right */}
      <div className="flex items-center gap-2 ml-auto relative z-10">
        <button
          onClick={handleMinimize}
          className="w-3 h-3 rounded-full hover:opacity-80 flex items-center justify-center transition-all group border-none outline-none"
          style={{ backgroundColor: '#FFBD2E' }}
        >
          <Minus className="w-2 h-2 text-yellow-900 opacity-0 group-hover:opacity-100 transition-opacity" />
        </button>
        <button
          disabled
          className="w-3 h-3 rounded-full flex items-center justify-center cursor-default opacity-50 border-none outline-none"
          style={{ backgroundColor: '#28C840' }}
        >
        </button>
        <button
          onClick={handleClose}
          className="w-3 h-3 rounded-full hover:opacity-80 flex items-center justify-center transition-all group border-none outline-none"
          style={{ backgroundColor: '#FF5F57' }}
        >
          <X className="w-2 h-2 text-red-900 opacity-0 group-hover:opacity-100 transition-opacity" />
        </button>
      </div>
    </div>
  );
}

// ui/src/components/TitleBar.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { WebviewWindow } from '@tauri-apps/api/webviewWindow';
  
  const appWindowInstance = WebviewWindow.getCurrent();

  async function handleClose() {
    await appWindowInstance.close();
  }

  async function handleMinimize() {
    await appWindowInstance.minimize();
  }

  async function handleDragStart(e: MouseEvent) {
    const target = e.target as HTMLElement;
    if (e.button === 0 && !target.closest('button, .traffic')) {
      e.preventDefault();
      try {
        await appWindowInstance.startDragging();
      } catch (err) {
        console.warn('Failed to start dragging:', err);
      }
    }
  }

  onMount(() => {
    // Apply cursor to titlebar - Konata Izumi
    const applyCursor = () => {
      const cursorUrl = 'url(/cursors/sizeall.cur), move';
      
      const titlebar = document.querySelector('.titlebar') as HTMLElement;
      const draggable = document.querySelector('.draggable') as HTMLElement;
      
      if (titlebar) {
        titlebar.style.setProperty('cursor', cursorUrl, 'important');
      }
      if (draggable) {
        draggable.style.setProperty('cursor', cursorUrl, 'important');
      }
    };
    
    setTimeout(() => applyCursor(), 50);
    setTimeout(() => applyCursor(), 100);
    setTimeout(() => applyCursor(), 200);
  });
</script>

<div
  class="titlebar"
  style="height: 56px; display: flex; align-items: center; justify-content: space-between; padding: 0 20px; border-bottom: 1px solid rgba(255, 255, 255, 0.2); flex-shrink: 0; position: relative; background-color: rgba(0, 0, 0, 0.04); border-top-left-radius: 10px; border-top-right-radius: 10px; overflow: hidden;"
  data-tauri-drag-region
  on:mousedown={handleDragStart}
  role="banner"
>
  <!-- Title - centered -->
  <div
    class="draggable"
    style="position: absolute; left: 0; right: 0; top: 0; bottom: 0; display: flex; align-items: center; justify-content: center; gap: 8px; font-weight: bold; font-size: 16px; color: white; pointer-events: none;"
    data-tauri-drag-region
  >
    <img src="/icon.ico" alt="File Extractor Icon" style="width: 20px; height: 20px; pointer-events: none;" />
    File Extractor
  </div>

  <!-- Window controls on the right -->
  <div style="display: flex; align-items: center; gap: 8px; margin-left: auto; position: relative; z-index: 10;">
    <button
      on:click={handleMinimize}
      class="traffic min"
      title="Minimize"
    >
      <svg width="8" height="8" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="opacity: 0; transition: opacity 0.2s;">
        <line x1="5" y1="12" x2="19" y2="12"></line>
      </svg>
    </button>
    <button
      disabled
      class="traffic max"
      title="Maximize (disabled)"
    >
    </button>
    <button
      on:click={handleClose}
      class="traffic close"
      title="Close"
    >
      <svg width="8" height="8" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="opacity: 0; transition: opacity 0.2s;">
        <line x1="18" y1="6" x2="6" y2="18"></line>
        <line x1="6" y1="6" x2="18" y2="18"></line>
      </svg>
    </button>
  </div>
</div>

<style>
  .titlebar {
    user-select: none;
  }
  
  .draggable {
    /* Cursor is set via JavaScript based on theme */
  }
  
  .traffic {
    width: 10px;
    height: 10px;
    border-radius: 50%;
    border: none;
    outline: none;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: all 0.2s ease;
    cursor: url('/cursors/hand.cur'), pointer !important;
    padding: 0;
  }
  
  .traffic:hover {
    transform: scale(1.15);
  }
  
  .traffic:hover svg {
    opacity: 1 !important;
  }
  
  .traffic:disabled {
    cursor: url('/cursors/no.cur'), not-allowed !important;
  }
  
  .traffic:disabled:hover {
    transform: none;
  }
  
  .min {
    background: #ffbd2e;
  }
  
  .max {
    background: #28c840;
  }
  
  .close {
    background: #ff5f57;
  }
</style>
